### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by justchokingaround** [Adolar0042/dots#1]
![image](https://github.com/Adolar0042/dots/assets/44473782/84694a74-43db-477a-bccd-ffe72e162f1c)

**Comment by Adolar0042** [comment]
![image](https://github.com/Adolar0042/dots/assets/39769465/a5aba37f-de14-4ec4-b49e-e47c60e24b23)

**Comment by justchokingaround** [comment]
![image](https://github.com/Adolar0042/dots/assets/44473782/b794d513-e447-49a1-b214-df02fc7cc6df)

**Comment by justchokingaround** [comment]
![image](https://github.com/Adolar0042/dots/assets/44473782/9be79a03-22a7-421c-b592-ce12ba2b67b8)

**Comment by Adolar0042** [comment]
when my era of linux comes I will upload proper dots :prayge:

**Comment by justchokingaround** [comment]
:pray:

**Comment by justchokingaround** [comment]
long awaited arc

**Comment by Adolar0042** [comment]
Still in planning with no eta for release tho
